using ConnectedOps.Domain.Assets;

namespace ConnectedOps.Application.Assets;

public sealed record AssetDto(
    Guid Id,
    string AssetNumber,
    string Name,
    string? SerialNumber,
    string? InternalCode,
    string? Barcode,
    string? RfidTag,
    Guid CategoryId,
    string? CategoryName,
    Guid AssetTypeId,
    string? AssetTypeName,
    string? Make,
    string? Model,
    string? Year,
    AssetOwnershipType OwnershipType,
    AssetStatus Status,
    AssetCondition Condition,
    AssetAssignmentType AssignmentType,
    Guid? CurrentBranchId,
    string? CurrentBranchName,
    Guid? CurrentLocationId,
    string? CurrentLocationName,
    Guid? DepartmentId,
    string? DepartmentName,
    Guid? TeamId,
    string? TeamName,
    Guid? CurrentCustodianEmployeeId,
    string? CurrentCustodianEmployeeName,
    Guid? CurrentAssignedVehicleId,
    string? CurrentAssignedVehiclePlate,
    decimal? PurchaseCost,
    DateTime? PurchaseDate,
    DateTime? WarrantyExpiryDate,
    DateTime? NextInspectionDueUtc,
    DateTime? NextCalibrationDueUtc,
    decimal TotalUsageHours,
    bool IsActive,
    DateTime CreatedAtUtc);

public sealed record AssetDetailDto(
    Guid Id,
    string AssetNumber,
    string Name,
    string? Description,
    string? SerialNumber,
    string? InternalCode,
    string? Barcode,
    string? RfidTag,
    Guid CategoryId,
    string? CategoryName,
    Guid AssetTypeId,
    string? AssetTypeName,
    string? Make,
    string? Model,
    string? Year,
    AssetOwnershipType OwnershipType,
    AssetStatus Status,
    AssetCondition Condition,
    AssetAssignmentType AssignmentType,
    Guid? CurrentBranchId,
    string? CurrentBranchName,
    Guid? CurrentLocationId,
    string? CurrentLocationName,
    Guid? DepartmentId,
    string? DepartmentName,
    Guid? TeamId,
    string? TeamName,
    Guid? CurrentCustodianEmployeeId,
    string? CurrentCustodianEmployeeName,
    Guid? CurrentAssignedVehicleId,
    string? CurrentAssignedVehiclePlate,
    decimal? PurchaseCost,
    DateTime? PurchaseDate,
    string? VendorName,
    DateTime? WarrantyExpiryDate,
    string? WarrantyNotes,
    DateTime? NextInspectionDueUtc,
    DateTime? NextCalibrationDueUtc,
    decimal TotalUsageHours,
    int? ExpectedLifespanMonths,
    bool IsCritical,
    bool IsActive,
    DateTime CreatedAtUtc,
    DateTime? UpdatedAtUtc,
    List<AssetIdentifierDto>? Identifiers,
    List<AssetLocationHistoryDto>? LocationHistory,
    List<AssetNoteDto>? Notes);

public sealed record AssetListFilter(
    string? SearchTerm = null,
    Guid? CategoryId = null,
    Guid? AssetTypeId = null,
    AssetStatus? Status = null,
    AssetCondition? Condition = null,
    AssetAssignmentType? AssignmentType = null,
    Guid? BranchId = null,
    Guid? LocationId = null,
    Guid? DepartmentId = null,
    Guid? TeamId = null,
    Guid? CustodianEmployeeId = null,
    Guid? AssignedVehicleId = null,
    bool? RequiresInspectionSoon = null,
    bool? RequiresCalibrationSoon = null,
    int PageNumber = 1,
    int PageSize = 20);

public sealed record CreateAssetRequest(
    string AssetNumber,
    string Name,
    string? Description,
    string? SerialNumber,
    string? InternalCode,
    string? Barcode,
    string? RfidTag,
    Guid CategoryId,
    Guid AssetTypeId,
    string? Make,
    string? Model,
    string? Year,
    AssetOwnershipType OwnershipType = AssetOwnershipType.CompanyOwned,
    AssetCondition Condition = AssetCondition.Good,
    Guid? BranchId = null,
    Guid? LocationId = null,
    Guid? DepartmentId = null,
    Guid? TeamId = null,
    decimal? PurchaseCost = null,
    DateTime? PurchaseDate = null,
    string? VendorName = null,
    DateTime? WarrantyExpiryDate = null,
    string? WarrantyNotes = null,
    DateTime? NextInspectionDueUtc = null,
    DateTime? NextCalibrationDueUtc = null,
    int? ExpectedLifespanMonths = null,
    bool IsCritical = false);

public sealed record UpdateAssetRequest(
    string Name,
    string? Description,
    string? SerialNumber,
    string? InternalCode,
    string? Barcode,
    string? RfidTag,
    Guid CategoryId,
    Guid AssetTypeId,
    string? Make,
    string? Model,
    string? Year,
    AssetOwnershipType OwnershipType,
    Guid? DepartmentId,
    Guid? TeamId,
    decimal? PurchaseCost,
    DateTime? PurchaseDate,
    string? VendorName,
    DateTime? WarrantyExpiryDate,
    string? WarrantyNotes,
    int? ExpectedLifespanMonths,
    bool IsCritical,
    bool IsActive);

public sealed record ChangeAssetStatusRequest(
    AssetStatus NewStatus,
    string Reason);

public sealed record UpdateAssetLocationRequest(
    Guid? BranchId,
    Guid? LocationId,
    string? Reason);

public sealed record AssetLocationHistoryDto(
    Guid Id,
    Guid AssetId,
    Guid? BranchId,
    string? BranchName,
    Guid? LocationId,
    string? LocationName,
    DateTime EffectiveFromUtc,
    DateTime? EffectiveToUtc,
    string? ChangedByUserId,
    string? ChangedByUserName,
    string? Reason);

public sealed record AssetNoteDto(
    Guid Id,
    Guid AssetId,
    string Note,
    DateTime CreatedAtUtc,
    string? CreatedByUserId,
    string? CreatedByUserName);

public sealed record AddAssetNoteRequest(
    string Note);
